name: Cypress Tests
on:
  push:
    branches:
      - main
      - testing/*
      - release/*
      - features/*
  pull_request:
    branches:
      - main
      - testing/*
      - release/*
      - features/*
  workflow_dispatch:
jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
            cypress-tests/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Cypress in cypress-tests
        run: |
          cd cypress-tests
          npm ci --legacy-peer-deps

      - name: Install main project's dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build

      - name: Start project
        run: |
          npm run start -- --port 8080 &

      - name: Run Cypress tests
        run: |
          cd cypress-tests
          npm run test

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress-tests/cypress/screenshots/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: cypress-videos
          path: cypress-tests/cypress/videos/
          retention-days: 30
