name: Cypress Tests
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Cypress and Node modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Cypress
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app
        run: npm run start -- --port 8080 &

      - name: Wait for App
        run: npx wait-on 'http://localhost:8080'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:8080"
          component: true
          record: true
          record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
          auto-cancel-after-failures: 2

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
